name: env-database

services:
  postgres:
    image: postgres:latest
    container_name: postgres-development
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - C:\Docker\pgdev:/var/lib/postgresql/data
    ports:
      - "5555:5432"
