name: env-database

services:
  postgres:
    image: postgres:latest
    container_name: postgres-development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/data/development/pgdata_dev_env:/var/lib/postgresql/data
    ports:
      - "5555:5432"