version: '3.8'

services:
  mvm-score-archive-api:
    image: ${DOCKER_REGISTRY-}mvmscorearchiveapi
    container_name: archive-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - postgres
    networks:
      - archive-network-dev
      
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/data/dev/pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    networks:
      - archive-network-dev

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - archive-network-dev

networks:
  archive-network-dev:
    driver: bridge
