version: '3.8'

services:
  mvm-score-archive-api:
    image: ${DOCKER_REGISTRY-}mvmscorearchiveapi
    container_name: archive-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - archive-network-dev
      
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/data/dev/pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    networks:
      - archive-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]


networks:
  archive-network-dev:
    driver: bridge
