services:
  api:
    container_name: archive-api-dev
    image: ${DOCKER_REGISTRY-}mvmscorearchiveapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_HTTP_PORTS=5001
    # depends_on:
    #   database:
    #     condition: service_healthy
    volumes:
      - app_data:/app/data
    networks:
      - archive-network-dev
      
  database:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/data/dev/pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - archive-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - archive-network-dev

networks:
  archive-network-dev:
    driver: bridge

volumes:
  app_data:
