version: '3.8'

services:
  mvm-score-archive-api:
    image: ${DOCKER_REGISTRY-}mvmscorearchiveapi
    container_name: archive-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      database:
        condition: service_healthy
    networks:
      - archive-network
      
  postgres:
    image: postgres:latest
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/data/prod/pgdata:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    networks:
      - archive-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

networks:
  archive-network:
    driver: bridge
