// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvm.Score.Archive.Repository.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mvm.Score.Archive.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404132433_AddPartFilter")]
    partial class AddPartFilter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "clef", new[] { "none", "treble", "bass", "alto" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "orchestra", new[] { "unknown", "vorstufe", "juka", "staka" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tunings", new[] { "none", "c", "eb", "bb", "f", "a" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbPartDbScore", b =>
                {
                    b.Property<int>("DbScoreId")
                        .HasColumnType("integer")
                        .HasColumnName("db_score_id");

                    b.Property<int>("PartsId")
                        .HasColumnType("integer")
                        .HasColumnName("parts_id");

                    b.HasKey("DbScoreId", "PartsId")
                        .HasName("pk_db_part_db_score");

                    b.HasIndex("PartsId")
                        .HasDatabaseName("ix_db_part_db_score_parts_id");

                    b.ToTable("db_part_db_score", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbArranger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_arranges");

                    b.ToTable("arranges", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbComposer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_composers");

                    b.ToTable("composers", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Clef")
                        .HasColumnType("integer")
                        .HasColumnName("clef");

                    b.Property<int?>("FallbackPartId")
                        .HasColumnType("integer")
                        .HasColumnName("fallback_part_id");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<int?>("Part")
                        .HasColumnType("integer")
                        .HasColumnName("part");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Tuning")
                        .HasColumnType("integer")
                        .HasColumnName("tuning");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("FallbackPartId")
                        .HasDatabaseName("ix_parts_fallback_part_id");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPartFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_name");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_part_filters");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_part_filters_created_by_user_id");

                    b.ToTable("part_filters", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPartFilterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartFilterId")
                        .HasColumnType("integer")
                        .HasColumnName("part_filter_id");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_part_filter_items");

                    b.HasIndex("PartFilterId")
                        .HasDatabaseName("ix_part_filter_items_part_filter_id");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_part_filter_items_part_id");

                    b.ToTable("part_filter_items", (string)null);
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArrangerId")
                        .HasColumnType("integer")
                        .HasColumnName("arranger_id");

                    b.Property<int>("ComposerId")
                        .HasColumnType("integer")
                        .HasColumnName("composer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.Property<int>("Orchestra")
                        .HasColumnType("integer")
                        .HasColumnName("orchestra");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("ArrangerId")
                        .HasDatabaseName("ix_scores_arranger_id");

                    b.HasIndex("ComposerId")
                        .HasDatabaseName("ix_scores_composer_id");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("DbPartDbScore", b =>
                {
                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbScore", null)
                        .WithMany()
                        .HasForeignKey("DbScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_db_part_db_score_scores_db_score_id");

                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbPart", null)
                        .WithMany()
                        .HasForeignKey("PartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_db_part_db_score_parts_parts_id");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPart", b =>
                {
                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbPart", null)
                        .WithMany()
                        .HasForeignKey("FallbackPartId")
                        .HasConstraintName("fk_parts_parts_fallback_part_id");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPartFilterItem", b =>
                {
                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbPartFilter", null)
                        .WithMany("PartFilterItems")
                        .HasForeignKey("PartFilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_filter_items_part_filters_part_filter_id");

                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbPart", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_filter_items_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbScore", b =>
                {
                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbArranger", "Arranger")
                        .WithMany("Scores")
                        .HasForeignKey("ArrangerId")
                        .HasConstraintName("fk_scores_arranges_arranger_id");

                    b.HasOne("Mvm.Score.Archive.Repository.DbEntities.DbComposer", "Composer")
                        .WithMany("Scores")
                        .HasForeignKey("ComposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_composers_composer_id");

                    b.Navigation("Arranger");

                    b.Navigation("Composer");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbArranger", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbComposer", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Mvm.Score.Archive.Repository.DbEntities.DbPartFilter", b =>
                {
                    b.Navigation("PartFilterItems");
                });
#pragma warning restore 612, 618
        }
    }
}
