name: Pull request workflow

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write
  packages: write

env:
  DOTNET_VERSION: "10.0.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup NuGet Authentication
        run: |
          dotnet nuget add source \
            --username $GITHUB_ACTOR \
            --password ${{ secrets.NUGET_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/jakoherr/index.json"

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal
